{-|
Module      : Analyzer
Description : Static analysis engine using Symbolic Execution and Z3.

This module is responsible for analyzing the AST generated by the Parser.
It uses a hybrid approach: concrete evaluation where possible, and symbolic
execution to explore different program paths. It translates program states 
and compile-time contracts (invariants, pre/postconditions) into SMT queries
to mathematically prove the absence of safety violations (like division by zero, 
array out-of-bounds) and contract breaches.
-}

-- if we pass const cptr we don't have to invalidate
-- for invar -> while
-- seperate errors from unkowns
-- break continue logic
module Analyzer where

import Parser
import qualified Data.Map as M
import Control.Monad
import Control.Monad.State
import Data.Maybe 
import Data.List 
import Z3.Monad as Z3
import Text.Megaparsec.Pos

-- ============================================================================
-- STATE & DATA TYPES
-- ============================================================================

type Addr = Int

-- | Represents values held in memory during concrete/hybrid execution.
data Value 
    = VInt Integer 
    | VDouble Double     
    | VChar Char         
    | VBool Bool 
    | VArray [Value]     
    | VAddr Addr         
    | VUnknown
    deriving (Show, Eq)

-- | The environment maps variable names to their memory addresses.
type SymEnv = M.Map String Addr      

-- | The heap maps memory addresses to concrete or symbolic values.
type Heap   = M.Map Addr Value       

-- | The symbolic store maps addresses to symbolic expressions for SMT solving.
type SymStore = M.Map Addr Expr      

-- | A pre-computed summary of a function's behavior.
data FuncSummary = FuncSummary
    { modifiedParams :: [String] -- ^ Which parameter names are mutated (pointers/arrays)
    , implicitPosts  :: [Expr]   -- ^ Derived logical facts about the return value ('res')
    } deriving (Show, Eq)

-- Add this to AnalyzerState:
-- 

data AnalyzerState = AnalyzerState
    { env        :: SymEnv                        -- ^ Current variable scope mapping
    , heap       :: Heap                          -- ^ Current state of memory
    , heapTypes  :: M.Map Addr Type               -- ^ Type metadata for memory addresses
    , structs    :: M.Map String [(Type, String)] -- ^ Struct definitions
    , unions     :: M.Map String [(Type, String)] -- ^ Union definitions
    , nextAddr   :: Addr                          -- ^ Pointer for the next memory allocation
    , facts      :: [Expr]                        -- ^ Accumulated logical facts (Path Conditions)
    , funcs      :: M.Map String Function         -- ^ Global function definitions
    , violations :: [(SourcePos, String, Expr)]   -- ^ Collected contract/safety failures
    , returnVal  :: Maybe Value                   -- ^ Holds the return value during block evaluation
    , summaries  :: M.Map String FuncSummary
    } deriving (Show)

-- | The primary Monad stack for the Analyzer: State over IO (required by Z3).
type Analyzer a = StateT AnalyzerState IO a
  
type FuncEnv   = M.Map String Function
type StructEnv = M.Map String [(Type, String)]
type UnionEnv  = M.Map String [(Type, String)]
type HeapTypes = M.Map Addr Type

-- | A snapshot of the memory layout rules and types.
data Layout = Layout
    { lStructs :: StructEnv
    , lUnions  :: UnionEnv
    , lTypes   :: HeapTypes
    , lEnv     :: SymEnv
    }

getLayout :: Analyzer Layout
getLayout = do
    s <- get
    return $ Layout (structs s) (unions s) (heapTypes s) (env s)


-- ============================================================================
-- MEMORY LAYOUT & TYPE HELPERS
-- ============================================================================

-- | Calculates the byte size of a given type.
sizeOf :: Layout -> Type -> Int
sizeOf l ty = case ty of
    Int -> 1; Double -> 1; Bool -> 1; Char -> 1; Void -> 1; Ptr _ -> 1; Enum _ -> 1
    ConstT t -> sizeOf l t
    Array t (Just (Expr _ (IntLit n))) -> fromIntegral n * sizeOf l t
    Array t _ -> sizeOf l t
    Struct n -> case M.lookup n (lStructs l) of
        Just fields -> sum (map (\(t,_) -> sizeOf l t) fields)
        Nothing -> 1
    Union n -> case M.lookup n (lUnions l) of
        Just fields -> if null fields then 1 else maximum (map (\(t,_) -> sizeOf l t) fields)
        Nothing -> 1

-- | Calculates the memory offset of a specific property within a struct/union.
offsetOf :: Layout -> Type -> String -> Maybe Int
offsetOf l ty prop = case ty of
    Struct n -> do
        fields <- M.lookup n (lStructs l)
        let go [] = Nothing
            go ((t, name):fs)
                | name == prop = Just 0
                | otherwise    = (+ sizeOf l t) <$> go fs
        go fields
    Union _ -> Just 0 
    ConstT t -> offsetOf l t prop
    _ -> Nothing

-- | Retrieves the type of a specific field within a struct or union.
fieldType :: Layout -> Type -> String -> Maybe Type
fieldType l ty prop = case ty of
    Struct n -> M.lookup n (lStructs l) >>= lookup prop . map (\(t,nm) -> (nm,t))
    Union n  -> M.lookup n (lUnions l)  >>= lookup prop . map (\(t,nm) -> (nm,t))
    ConstT t -> fieldType l t prop
    _ -> Nothing

-- | Infers the type of an expression based on the current layout.
typeOf :: Layout -> Expr -> Maybe Type
typeOf l (Expr _ node) = case node of
    Var x        -> M.lookup x (lEnv l) >>= \addr -> M.lookup addr (lTypes l)
    Field e prop -> typeOf l e >>= \ty -> fieldType l ty prop
    Index e _    -> typeOf l e >>= \ty -> case ty of
        Array t _ -> Just t
        Ptr t     -> Just t
        _         -> Nothing
    Deref e      -> typeOf l e >>= \ty -> case ty of
        Ptr t     -> Just t
        Array t _ -> Just t
        _         -> Nothing
    AddrOf e     -> typeOf l e >>= \ty -> Just (Ptr ty)
    _            -> Nothing

-- | Evaluates an expression to find its corresponding memory address (l-value).
lvalue :: Layout -> Heap -> Expr -> Maybe Addr
lvalue l heap (Expr _ node) = case node of
    Var x        -> M.lookup x (lEnv l)
    Field e prop -> do
        baseAddr <- lvalue l heap e
        baseTy   <- typeOf l e
        off      <- offsetOf l baseTy prop
        return (baseAddr + off)
    Index e idx  -> do
        baseAddr <- lvalue l heap e
        baseTy   <- typeOf l e
        let elemSz = case baseTy of
                Array t _ -> sizeOf l t
                Ptr t     -> sizeOf l t
                _         -> 1
        idxVal <- case evalPure l heap idx of
            VInt i -> Just (fromIntegral i)
            _      -> Nothing
        return (baseAddr + idxVal * elemSz)
    Deref e      -> case evalPure l heap e of
        VAddr addr -> Just addr
        _          -> Nothing
    _ -> Nothing

findBaseVars :: Layout -> Addr -> [(String, Addr, Type)]
findBaseVars l target =
    [ (name, baseAddr, ty)
    | (name, baseAddr) <- M.toList (lEnv l)
    , Just ty <- [M.lookup baseAddr (lTypes l)]
    , target >= baseAddr && target < baseAddr + sizeOf l ty
    ]

buildExpr :: Layout -> Type -> Addr -> Addr -> Expr -> Maybe Expr
buildExpr l ty baseAddr targetAddr currentExpr
    | baseAddr == targetAddr = Just currentExpr
    | otherwise = case ty of
        Struct n -> do
            fields <- M.lookup n (lStructs l)
            let findField [] _ = Nothing
                findField ((ft, fname):fs) currentOff
                    | targetAddr >= baseAddr + currentOff && targetAddr < baseAddr + currentOff + sizeOf l ft =
                        buildExpr l ft (baseAddr + currentOff) targetAddr (genExpr (Field currentExpr fname))
                    | otherwise = findField fs (currentOff + sizeOf l ft)
            findField fields 0
        Union n -> do
            fields <- M.lookup n (lUnions l)
            case fields of
                ((ft, fname):_) -> buildExpr l ft baseAddr targetAddr (genExpr (Field currentExpr fname))
                _               -> Nothing
        Array t _ -> do
            let elemSz = sizeOf l t
            if elemSz == 0 then Nothing else do
                let idx = (targetAddr - baseAddr) `div` elemSz
                buildExpr l t (baseAddr + idx * elemSz) targetAddr (genExpr (Index currentExpr (genExpr (IntLit (fromIntegral idx)))))
        ConstT t -> buildExpr l t baseAddr targetAddr currentExpr
        _        -> Nothing

reverseLval :: Layout -> Addr -> [Expr]
reverseLval l target = do
    (name, baseAddr, ty) <- findBaseVars l target
    case buildExpr l ty baseAddr target (genExpr (Var name)) of
        Just expr -> [expr]
        Nothing   -> []


-- ============================================================================
-- PURE EVALUATION & ARITHMETIC
-- ============================================================================

applyOp :: String -> Value -> Value -> Value
applyOp "+" (VInt a) (VInt b)       = VInt (a + b)
applyOp "+" (VDouble a) (VDouble b) = VDouble (a + b)
applyOp "+" (VInt a) (VDouble b)    = VDouble (fromIntegral a + b)
applyOp "+" (VDouble a) (VInt b)    = VDouble (a + fromIntegral b)
applyOp "+" (VAddr a) (VInt b)      = VAddr (a + fromIntegral b)
applyOp "+" (VInt a) (VAddr b)      = VAddr (fromIntegral a + b)
applyOp "-" (VInt a) (VInt b)       = VInt (a - b)
applyOp "-" (VDouble a) (VDouble b) = VDouble (a - b)
applyOp "-" (VInt a) (VDouble b)    = VDouble (fromIntegral a - b)
applyOp "-" (VDouble a) (VInt b)    = VDouble (a - fromIntegral b)
applyOp "-" (VAddr a) (VInt b)      = VAddr (a - fromIntegral b)
applyOp "-" (VAddr a) (VAddr b)     = VInt (fromIntegral (a - b))
applyOp "*" (VInt a) (VInt b)       = VInt (a * b)
applyOp "*" (VDouble a) (VDouble b) = VDouble (a * b)
applyOp "*" (VInt a) (VDouble b)    = VDouble (fromIntegral a * b)
applyOp "*" (VDouble a) (VInt b)    = VDouble (a * fromIntegral b)
applyOp "/" (VInt a) (VInt b)       | b /= 0 = VInt (a `div` b)
applyOp "/" (VDouble a) (VDouble b) | b /= 0.0 = VDouble (a / b)
applyOp ">" (VInt a) (VInt b)       = VBool (a > b)
applyOp ">" (VDouble a) (VDouble b) = VBool (a > b)
applyOp "<" (VInt a) (VInt b)       = VBool (a < b)
applyOp "<" (VDouble a) (VDouble b) = VBool (a < b)
applyOp ">=" (VInt a) (VInt b)      = VBool (a >= b)
applyOp ">=" (VDouble a) (VDouble b)= VBool (a >= b)
applyOp "<=" (VInt a) (VInt b)      = VBool (a <= b)
applyOp "<=" (VDouble a) (VDouble b)= VBool (a <= b)
applyOp "==" (VInt a) (VInt b)      = VBool (a == b)
applyOp "==" (VDouble a) (VDouble b)= VBool (a == b)
applyOp "==" (VChar a) (VChar b)    = VBool (a == b)
applyOp "==" (VBool a) (VBool b)    = VBool (a == b)
applyOp "==" (VAddr a) (VAddr b)    = VBool (a == b) 
applyOp "!=" a b                    = case applyOp "==" a b of VBool res -> VBool (not res); _ -> VUnknown
applyOp "&&" (VBool a) (VBool b)    = VBool (a && b)
applyOp "||" (VBool a) (VBool b)    = VBool (a || b)
applyOp _ _ _                       = VUnknown

applyUnOp :: String -> Value -> Value
applyUnOp "-" (VInt a)    = VInt (-a)
applyUnOp "-" (VDouble a) = VDouble (-a)
applyUnOp "!" (VBool b)   = VBool (not b)
applyUnOp _ _             = VUnknown

-- | Evaluates an expression concretely where possible, returning VUnknown if symbolic.
evalPure :: Layout -> Heap -> Expr -> Value
evalPure l heap expr@(Expr _ node) = case node of
    IntLit n      -> VInt n
    DoubleLit d   -> VDouble d
    CharLit c     -> VChar c
    BoolLit b     -> VBool b
    AddrOf e      -> case lvalue l heap e of Just addr -> VAddr addr; Nothing -> VUnknown
    Var _         -> readLval l heap expr
    Field _ _     -> readLval l heap expr
    Index _ _     -> readLval l heap expr
    Deref _       -> readLval l heap expr
    BinOp op e1 e2-> applyOp op (evalPure l heap e1) (evalPure l heap e2)
    UnOp op e     -> applyUnOp op (evalPure l heap e)
    Ternary c t e -> case evalPure l heap c of 
                       VBool True  -> evalPure l heap t
                       VBool False -> evalPure l heap e
                       _           -> VUnknown
    _             -> VUnknown

readLval :: Layout -> Heap -> Expr -> Value
readLval l heap e = case lvalue l heap e of
    Just addr -> M.findWithDefault VUnknown addr heap
    Nothing   -> VUnknown


-- ============================================================================
-- EXPRESSION MANIPULATION & SIMPLIFICATION
-- ============================================================================

substituteExpr :: Expr -> Expr -> Expr -> Expr
substituteExpr target replacement inExpr@(Expr pos node) =
    let isMatch = case (node, target) of
            (Var x, Expr _ (Var y)) -> x == y
            _ -> inExpr == target
    in if isMatch then replacement else case node of
        BinOp op e1 e2 -> Expr pos (BinOp op (substituteExpr target replacement e1) (substituteExpr target replacement e2))
        UnOp op e      -> Expr pos (UnOp op (substituteExpr target replacement e))
        Call fname args-> Expr pos (Call fname (map (substituteExpr target replacement) args))
        Index e1 e2    -> Expr pos (Index (substituteExpr target replacement e1) (substituteExpr target replacement e2))
        Field e prop   -> Expr pos (Field (substituteExpr target replacement e) prop)
        AddrOf e       -> Expr pos (AddrOf (substituteExpr target replacement e))
        PreInc e       -> Expr pos (PreInc (substituteExpr target replacement e))
        PostInc e      -> Expr pos (PostInc (substituteExpr target replacement e))
        PreDec e       -> Expr pos (PreDec (substituteExpr target replacement e))
        PostDec e      -> Expr pos (PostDec (substituteExpr target replacement e))
        Ternary c t e  -> Expr pos (Ternary (substituteExpr target replacement c) (substituteExpr target replacement t) (substituteExpr target replacement e))
        Deref e -> case substituteExpr target replacement e of 
                     Expr _ (AddrOf inner) -> inner
                     other -> Expr pos (Deref other)
        _ -> inExpr

substituteMany :: [(Expr, Expr)] -> Expr -> Expr
substituteMany subs inExpr = foldl (\expr (targ, repl) -> substituteExpr targ repl expr) inExpr subs

simplifyBool :: Expr -> Expr
simplifyBool inExpr@(Expr pos node) = case node of
    BinOp "&&" (Expr _ (BoolLit False)) _ -> Expr pos (BoolLit False)
    BinOp "&&" _ (Expr _ (BoolLit False)) -> Expr pos (BoolLit False)
    BinOp "&&" (Expr _ (BoolLit True)) e  -> simplifyBool e
    BinOp "&&" e (Expr _ (BoolLit True))  -> simplifyBool e
    BinOp "||" (Expr _ (BoolLit True)) _  -> Expr pos (BoolLit True)
    BinOp "||" _ (Expr _ (BoolLit True))  -> Expr pos (BoolLit True)
    BinOp "||" (Expr _ (BoolLit False)) e -> simplifyBool e
    BinOp "||" e (Expr _ (BoolLit False)) -> simplifyBool e
    BinOp "&&" e1 e2 -> 
        let e1' = simplifyBool e1; e2' = simplifyBool e2 
        in if e1' == genExpr (BoolLit False) || e2' == genExpr (BoolLit False) then Expr pos (BoolLit False) 
           else if e1' == genExpr (BoolLit True) then e2' 
           else if e2' == genExpr (BoolLit True) then e1' 
           else Expr pos (BinOp "&&" e1' e2')
    BinOp "||" e1 e2 -> 
        let e1' = simplifyBool e1; e2' = simplifyBool e2 
        in if e1' == genExpr (BoolLit True) || e2' == genExpr (BoolLit True) then Expr pos (BoolLit True) 
           else if e1' == genExpr (BoolLit False) then e2' 
           else if e2' == genExpr (BoolLit False) then e1' 
           else Expr pos (BinOp "||" e1' e2')
    UnOp "!" (Expr _ (BinOp ">" a b))  -> Expr pos (BinOp "<=" a b)
    UnOp "!" (Expr _ (BinOp "<" a b))  -> Expr pos (BinOp ">=" a b)
    UnOp "!" (Expr _ (BinOp ">=" a b)) -> Expr pos (BinOp "<" a b)
    UnOp "!" (Expr _ (BinOp "<=" a b)) -> Expr pos (BinOp ">" a b)
    UnOp "!" (Expr _ (BinOp "==" a b)) -> Expr pos (BinOp "!=" a b)
    UnOp "!" (Expr _ (BinOp "!=" a b)) -> Expr pos (BinOp "==" a b)
    UnOp "!" (Expr _ (BoolLit True))   -> Expr pos (BoolLit False)
    UnOp "!" (Expr _ (BoolLit False))  -> Expr pos (BoolLit True)
    _ -> inExpr

-- | Partially evaluates an expression, simplifying nodes where concrete values are known.
partialEval :: Layout -> Heap -> Expr -> Expr
partialEval l heap expr@(Expr pos node) = case node of
    Var _handleCallback -> toLit expr
    Field e p           -> case toLit expr of Expr _ (Field _ _) -> Expr pos (Field (partialEval l heap e) p); lit -> lit
    Index e1 e2         -> case toLit expr of Expr _ (Index _ _) -> Expr pos (Index (partialEval l heap e1) (partialEval l heap e2)); lit -> lit
    Deref e             -> case toLit expr of Expr _ (Deref _)   -> Expr pos (Deref (partialEval l heap e)); lit -> lit
    BinOp op e1 e2 -> 
        let e1' = partialEval l heap e1; e2' = partialEval l heap e2
        in case (e1', e2') of
            (Expr _ (IntLit a), Expr _ (IntLit b)) -> case applyOp op (VInt a) (VInt b) of 
                                                        VInt n -> Expr pos (IntLit n); 
                                                        VBool x -> Expr pos (BoolLit x); 
                                                        _ -> Expr pos (BinOp op e1' e2')
            (Expr _ (BoolLit a), Expr _ (BoolLit b)) -> case applyOp op (VBool a) (VBool b) of 
                                                          VBool x -> Expr pos (BoolLit x); 
                                                          _ -> Expr pos (BinOp op e1' e2')
            (Expr _ (BoolLit True), right) | op == "&&" -> right
            (left, Expr _ (BoolLit True))  | op == "&&" -> left
            (Expr _ (BoolLit False), _)    | op == "&&" -> Expr pos (BoolLit False)
            (_, Expr _ (BoolLit False))    | op == "&&" -> Expr pos (BoolLit False)
            (Expr _ (BoolLit True), _)     | op == "||" -> Expr pos (BoolLit True)
            (_, Expr _ (BoolLit True))     | op == "||" -> Expr pos (BoolLit True)
            (Expr _ (BoolLit False), right)| op == "||" -> right
            (left, Expr _ (BoolLit False)) | op == "||" -> left
            _ -> Expr pos (BinOp op e1' e2')
    UnOp op e -> 
        let e' = partialEval l heap e
        in case e' of 
             Expr _ (IntLit a)  -> case applyUnOp op (VInt a) of VInt n -> Expr pos (IntLit n); _ -> Expr pos (UnOp op e')
             Expr _ (BoolLit a) -> case applyUnOp op (VBool a) of VBool x -> Expr pos (BoolLit x); _ -> Expr pos (UnOp op e')
             _                  -> Expr pos (UnOp op e')
    Call fname args -> Expr pos (Call fname (map (partialEval l heap) args))
    Ternary c t e -> let c' = partialEval l heap c in case c' of 
                       Expr _ (BoolLit True)  -> partialEval l heap t
                       Expr _ (BoolLit False) -> partialEval l heap e
                       _                      -> Expr pos (Ternary c' (partialEval l heap t) (partialEval l heap e))
    _ -> expr
  where
    toLit e = case readLval l heap e of 
                VInt n    -> Expr pos (IntLit n)
                VBool b   -> Expr pos (BoolLit b)
                VDouble d -> Expr pos (DoubleLit d)
                VChar c   -> Expr pos (CharLit c)
                _         -> e

splitAnds :: Expr -> [Expr]
splitAnds (Expr _ (BinOp "&&" e1 e2)) = splitAnds e1 ++ splitAnds e2
splitAnds e = [e]

extractVars :: Expr -> [String]
extractVars (Expr _ node) = case node of
    Var n         -> [n]
    BinOp _ e1 e2 -> extractVars e1 ++ extractVars e2
    UnOp _ e      -> extractVars e
    Ternary c t e -> extractVars c ++ extractVars t ++ extractVars e
    Call _ args   -> concatMap extractVars args
    Index e1 e2   -> extractVars e1 ++ extractVars e2
    Deref e       -> extractVars e
    AddrOf e      -> extractVars e
    Field e _     -> extractVars e
    _             -> []

-- | Extracts implicit safety obligations from an expression (e.g., preventing DivByZero).
extractSafety :: Layout -> t -> Expr -> [(SourcePos, String, Expr)]
extractSafety l funcs (Expr pos node) = case node of
    BinOp "/" e1 e2 -> 
        [(pos, "Division by Zero", genExpr (BinOp "!=" e2 (genExpr (IntLit 0))))] 
        ++ extractSafety l funcs e1 ++ extractSafety l funcs e2
    BinOp "%" e1 e2 -> 
        [(pos, "Modulo by Zero", genExpr (BinOp "!=" e2 (genExpr (IntLit 0))))] 
        ++ extractSafety l funcs e1 ++ extractSafety l funcs e2
    Index arr idx -> 
        let baseChecks = extractSafety l funcs arr ++ extractSafety l funcs idx
            boundsChecks = case typeOf l arr of
                Just (Array _ (Just (Expr _ (IntLit sz)))) -> 
                    [ (pos, "Array Index Out of Bounds", genExpr (BinOp "<" idx (genExpr (IntLit sz))))
                    , (pos, "Array Index Out of Bounds", genExpr (BinOp ">=" idx (genExpr (IntLit 0)))) 
                    ]
                _ -> []
        in boundsChecks ++ baseChecks
    Call _ args             -> concatMap (extractSafety l funcs) args
    ArrayUpdate arr idx val -> extractSafety l funcs arr ++ extractSafety l funcs idx ++ extractSafety l funcs val
    BinOp _ e1 e2           -> extractSafety l funcs e1 ++ extractSafety l funcs e2
    UnOp _ e                -> extractSafety l funcs e
    Ternary c t e           -> extractSafety l funcs c ++ extractSafety l funcs t ++ extractSafety l funcs e
    _                       -> []


-- ============================================================================
-- Z3 SMT SOLVER INTEGRATION
-- ============================================================================

z3SortForType :: Layout -> Maybe Type -> Z3 Z3.Sort
z3SortForType _ ty = case ty of
    Just Bool   -> mkBoolSort
    Just Double -> mkRealSort
    Just (Array _ _) -> do
        iSort <- mkIntSort
        vSort <- mkIntSort
        mkArraySort iSort vSort
    _ -> mkIntSort 

translateZ3 :: Layout -> FuncEnv -> Expr -> Z3 Z3.AST
translateZ3 l funcs (Expr _ node) = case node of
    IntLit n  -> mkIntNum n
    BoolLit b -> mkBool b
    DoubleLit d -> mkRealSort >>= mkNumeral (show d)
    Var x -> do
        sym <- mkStringSymbol x
        sorted <- z3SortForType l (typeOf l (genExpr node))
        mkVar sym sorted
    BinOp "+" e1 e2  -> do { a <- translateZ3 l funcs e1; b <- translateZ3 l funcs e2; mkAdd [a, b] }
    BinOp "-" e1 e2  -> do { a <- translateZ3 l funcs e1; b <- translateZ3 l funcs e2; mkSub [a, b] }
    BinOp "*" e1 e2  -> do { a <- translateZ3 l funcs e1; b <- translateZ3 l funcs e2; mkMul [a, b] }
    BinOp "/" e1 e2  -> do { a <- translateZ3 l funcs e1; b <- translateZ3 l funcs e2; mkDiv a b }
    BinOp "==" e1 e2 -> do { a <- translateZ3 l funcs e1; b <- translateZ3 l funcs e2; mkEq a b }
    BinOp "!=" e1 e2 -> do { a <- translateZ3 l funcs e1; b <- translateZ3 l funcs e2; eq <- mkEq a b; mkNot eq }
    BinOp "<" e1 e2  -> do { a <- translateZ3 l funcs e1; b <- translateZ3 l funcs e2; mkLt a b }
    BinOp "<=" e1 e2 -> do { a <- translateZ3 l funcs e1; b <- translateZ3 l funcs e2; mkLe a b }
    BinOp ">" e1 e2  -> do { a <- translateZ3 l funcs e1; b <- translateZ3 l funcs e2; mkGt a b }
    BinOp ">=" e1 e2 -> do { a <- translateZ3 l funcs e1; b <- translateZ3 l funcs e2; mkGe a b }
    BinOp "&&" e1 e2 -> do { a <- translateZ3 l funcs e1; b <- translateZ3 l funcs e2; mkAnd [a, b] }
    BinOp "||" e1 e2 -> do { a <- translateZ3 l funcs e1; b <- translateZ3 l funcs e2; mkOr [a, b] }
    UnOp "!" e       -> translateZ3 l funcs e >>= mkNot
    UnOp "-" e       -> translateZ3 l funcs e >>= mkUnaryMinus
    Ternary c t e -> do
        zC <- translateZ3 l funcs c
        zT <- translateZ3 l funcs t
        zE <- translateZ3 l funcs e
        mkIte zC zT zE

    Index arr idx -> do
        z3Arr <- translateZ3 l funcs arr
        z3Idx <- translateZ3 l funcs idx
        mkSelect z3Arr z3Idx

    ArrayUpdate arr idx val -> do
        z3Arr <- translateZ3 l funcs arr
        z3Idx <- translateZ3 l funcs idx
        z3Val <- translateZ3 l funcs val
        mkStore z3Arr z3Idx z3Val

    Call fname args -> do
        sym <- mkStringSymbol fname
        let retType = case M.lookup fname funcs of Just f -> Just (funcRetType f); Nothing -> Just Int
        
        retSort  <- z3SortForType l retType
        argSorts <- mapM (\arg -> z3SortForType l (typeOf l arg)) args
        funcDecl <- mkFuncDecl sym argSorts retSort
        
        if null args 
            then mkApp funcDecl []
            else do
                z3Args <- mapM (translateZ3 l funcs) args
                mkApp funcDecl z3Args

    _ -> mkStringSymbol (show node) >>= mkIntVar 

-- | Proves if a given condition logically follows from a set of known facts using Z3.
proveZ3 :: Layout -> FuncEnv -> [Expr] -> Expr -> IO Value
proveZ3 l funcs facts condition = evalZ3 $ do
    z3Facts <- mapM (translateZ3 l funcs) facts
    z3Cond  <- translateZ3 l funcs condition
    mapM_ assert z3Facts
    
    -- We prove the condition by asserting its negation and looking for a contradiction (Unsat)
    notCond <- mkNot z3Cond
    assert notCond
    res <- check
    case res of
        Unsat -> return (VBool True)  -- Negation is impossible; condition is proven TRUE
        Sat   -> return (VBool False) -- Found a model where condition is false
        Undef -> return VUnknown      -- SMT solver timed out or gave up


-- ============================================================================
-- SYMBOLIC EXECUTION ENGINE
-- ============================================================================

-- | Evaluates an expression, checking preconditions if a function call is encountered.
evalExpr :: Expr -> Analyzer Value
evalExpr e@(Expr callPos node) = do
    l         <- getLayout
    currHeap  <- gets heap
    currFacts <- gets facts
    currFuncs <- gets funcs

    case node of
        Call fname argExprs -> do
            case M.lookup fname currFuncs of
                Nothing -> return VUnknown
                Just funcDef -> do
                    let paramNames = map (\(Arg _ n) -> n) (funcArgs funcDef)
                    let subs = zip (map (genExpr . Var) paramNames) argExprs
                    case funcInvars funcDef of
                        Nothing     -> return ()
                        Just invars -> forM_ (concatMap splitAnds invars) $ \inv -> do
                            let callerScopeInv = substituteMany subs inv
                            let evalInv        = partialEval l currHeap callerScopeInv
                            let evalFacts      = map (partialEval l currHeap) currFacts
                            
                            isProven <- liftIO $ proveZ3 l currFuncs evalFacts evalInv
                            when (isProven == VBool False || isProven == VUnknown) $ 
                                modify (\s -> s { violations = ((callPos, "Precondition Failed in: " ++ fname, callerScopeInv) : violations s) })
                    return VUnknown
        BinOp op e1 e2 -> applyOp op <$> evalExpr e1 <*> evalExpr e2
        UnOp op ex     -> applyUnOp op <$> evalExpr ex
        Ternary c t ex -> do
            condVal <- evalExpr c
            case condVal of 
                VBool True  -> evalExpr t
                VBool False -> evalExpr ex
                _           -> return VUnknown
        _ -> return $ evalPure l currHeap e

-- | Symbolically evaluates an expression against a symbolic store.
symEval :: Layout -> Heap -> SymStore -> Expr -> Expr
symEval l heap store expr@(Expr pos node) = case node of
    Var _                   -> checkStore expr
    Field _ _               -> checkStore expr
    Deref _                 -> checkStore expr
    Index arr idx           -> Expr pos (Index (symEval l heap store arr) (symEval l heap store idx))
    ArrayUpdate arr idx val -> Expr pos (ArrayUpdate (symEval l heap store arr) (symEval l heap store idx) (symEval l heap store val))
    BinOp op e1 e2          -> Expr pos (BinOp op (symEval l heap store e1) (symEval l heap store e2))
    UnOp op e               -> Expr pos (UnOp op (symEval l heap store e))
    Call fname args         -> Expr pos (Call fname (map (symEval l heap store) args))
    Ternary c t e           -> Expr pos (Ternary (symEval l heap store c) (symEval l heap store t) (symEval l heap store e))
    _                       -> expr
  where
    checkStore e = case lvalue l heap e of
        Just addr -> M.findWithDefault (preserve e) addr store
        Nothing   -> preserve e
    preserve (Expr p n) = case n of
        Field e prop -> Expr p (Field (symEval l heap store e) prop)
        Index e i    -> Expr p (Index (symEval l heap store e) (symEval l heap store i))
        Deref e      -> Expr p (Deref (symEval l heap store e))
        _            -> Expr p n

-- | Core engine for exploring paths and verifying statements symbolically.
-- Returns lists representing distinct execution paths and safety obligations collected.
symExec :: Int -> FuncEnv -> Layout -> Addr -> Heap -> SymStore -> Expr -> [Stmt] 
        -> ([(Expr, Maybe Expr, SymStore)], [(Layout, Addr, SymStore, Expr)], [(Expr, SourcePos, String, Expr, Expr)])
symExec fuel _ _ _ _ _ pc _ | fuel <= 0 = 
    let abortCheck = genExpr (BoolLit False)
        msg = "Analysis aborted: Out of fuel (Path too complex or infinite loop)"
    in ([], [], [(pc, initialPos "<internal>", msg, abortCheck, abortCheck)])
symExec _ _ l nextA _ store pc [] = ([], [(l, nextA, store, pc)], []) 
symExec fuel funcs l nextA heap store pc (Stmt pos stmtNode : stmts) = 
    let f = fuel - 1 in
    case stmtNode of
        Decl _ ty x mExpr -> 
            let valExpr = case mExpr of 
                    Just (Expr _ (Call _ _)) -> genExpr (Var x)
                    Just e                   -> symEval l heap store e
                    Nothing                  -> genExpr (Var x)
                checks = case mExpr of 
                    Just e  -> map (\(p, msg, c) -> (pc, p, msg, c, symEval l heap store c)) (extractSafety l funcs e)
                    Nothing -> []
                sz = sizeOf l ty
                newL = l { lEnv = M.insert x nextA (lEnv l), lTypes = M.insert nextA ty (lTypes l) }
                newStore = M.insert nextA valExpr store
                (r, c, sChecks) = symExec f funcs newL (nextA + sz) heap newStore pc stmts
            in (r, c, checks ++ sChecks)
            
        Assign lhs e@(Expr _ (Call _ _)) -> 
            let evalRhs = lhs
                origChecks = extractSafety l funcs lhs ++ extractSafety l funcs e
                checks = map (\(p, msg, c) -> (pc, p, msg, c, symEval l heap store c)) origChecks
            in case lvalue l heap lhs of
                Just addr -> let (r, c, sChecks) = symExec f funcs l nextA heap (M.insert addr evalRhs store) pc stmts
                             in (r, c, checks ++ sChecks)
                Nothing   -> let (r, c, sChecks) = symExec f funcs l nextA heap store pc stmts
                             in (r, c, checks ++ sChecks)  

        Assign lhs e -> 
            let evalLhs = symEval l heap store lhs
                evalRhs = symEval l heap store e
                origChecks = extractSafety l funcs lhs ++ extractSafety l funcs e
                checks = map (\(p, msg, c) -> (pc, p, msg, c, symEval l heap store c)) origChecks
            in case lhs of
                Expr _ (Index baseArr idxExpr) -> 
                    case lvalue l heap baseArr of
                        Just baseAddr -> 
                            let evalIdx = symEval l heap store idxExpr
                                currentArrState = M.findWithDefault (symEval l heap M.empty baseArr) baseAddr store
                                newArrState = genExpr (ArrayUpdate currentArrState evalIdx evalRhs)
                                newStore = M.insert baseAddr newArrState store
                                (r, c, sChecks) = symExec f funcs l nextA heap newStore pc stmts
                            in (r, c, checks ++ sChecks)
                        Nothing -> 
                            let (r, c, sChecks) = symExec f funcs l nextA heap store pc stmts
                            in (r, c, checks ++ sChecks)
                _ -> case lvalue l heap lhs of
                    Just addr -> let (r, c, sChecks) = symExec f funcs l nextA heap (M.insert addr evalRhs store) pc stmts
                                 in (r, c, checks ++ sChecks)
                    Nothing   -> let (r, c, sChecks) = symExec f funcs l nextA heap store pc stmts
                                 in (r, c, checks ++ sChecks)

        ExprStmt expr -> 
            let origChecks = extractSafety l funcs expr
                checks = map (\(p, msg, c) -> (pc, p, msg, c, symEval l heap store c)) origChecks
                (r, c, sChecks) = symExec f funcs l nextA heap store pc stmts
            in (r, c, checks ++ sChecks)

        Return mExpr -> 
            let evalRet = fmap (symEval l heap store) mExpr
                checks = case mExpr of 
                    Just e  -> map (\(p, msg, c) -> (pc, p, msg, c, symEval l heap store c)) (extractSafety l funcs e)
                    Nothing -> []
            in ([(pc, evalRet, store)], [], checks)
        
        Block innerStmts ->
            let (retI, contI, checksI) = symExec f funcs l nextA heap store pc innerStmts
                restResults = map (\(lI, nI, stI, pI) -> symExec f funcs lI nI heap stI pI stmts) contI
                returns = retI ++ concatMap (\(r,_,_) -> r) restResults
                continues = concatMap (\(_,c,_) -> c) restResults
                checksRest = concatMap (\(_,_,c) -> c) restResults
            in (returns, continues, checksI ++ checksRest)
            
        If cond thn els ->
            let condVal = symEval l heap store cond
                checksC = map (\(p, msg, c) -> (pc, p, msg, c, symEval l heap store c)) (extractSafety l funcs cond)
                
                (retT, contT, checksT) = symExec f funcs l nextA heap store (genExpr (BinOp "&&" pc condVal)) thn
                (retF, contF, checksF) = symExec f funcs l nextA heap store (genExpr (BinOp "&&" pc (genExpr (UnOp "!" condVal)))) (fromMaybe [] els)
                
                mergeStores origStore stT stF = 
                    let keys = nub (M.keys stT ++ M.keys stF)
                        getVal st k = case M.lookup k st of
                            Just v -> v
                            Nothing -> case M.lookup k origStore of
                                Just ov -> ov
                                Nothing -> case reverseLval l k of
                                    (expr:_) -> symEval l heap origStore expr
                                    []       -> genExpr (Var ("_unk_addr_" ++ show k))
                    in M.fromList [ (k, genExpr (Ternary condVal (getVal stT k) (getVal stF k))) | k <- keys ]
                
                mergedCont = case (contT, contF) of
                    ([], []) -> []
                    (ts, []) -> ts
                    ([], fs) -> fs
                    
                    ([(lT, nT, stT, pcT)], [(lF, nF, stF, pcF)]) ->
                        let mergedStore = mergeStores store stT stF
                            mergedPc = genExpr (BinOp "||" pcT pcF)
                            maxNextA = max nT nF
                            mergedLayout = l { lTypes = M.union (lTypes lT) (lTypes lF)
                                             , lEnv   = M.union (lEnv lT) (lEnv lF) }
                        in [(mergedLayout, maxNextA, mergedStore, mergedPc)]
                        
                    (ts, fs) -> ts ++ fs 
                
                restResults = map (\(lI, nI, stI, pI) -> symExec f funcs lI nI heap stI pI stmts) mergedCont
                
                returns = retT ++ retF ++ concatMap (\(r,_,_) -> r) restResults
                continues = concatMap (\(_,c,_) -> c) restResults
                checksRest = concatMap (\(_,_,c) -> c) restResults
            in (returns, continues, checksC ++ checksT ++ checksF ++ checksRest)
            
        While cond Nothing body ->
            let unrollLimit = 5
                unrolledBlock = foldr (\_ acc -> [Stmt pos (If cond (body ++ acc) Nothing)]) [] [1..unrollLimit]

                boundCheckExpr = genExpr (UnOp "!" cond)
                checkStmt = Stmt pos (Decl Dynamic Bool "_bound_check" (Just boundCheckExpr))
                
                (ret, cont, checks) = symExec f funcs l nextA heap store pc (unrolledBlock ++ [checkStmt] ++ stmts)
                
                mapBoundError (p, oldMsg, readable, math)
                    | readable == boundCheckExpr = (p, "Loop unroll limit exceeded. Add invariants.", readable, math)
                    | otherwise = (p, oldMsg, readable, math)
                    
            in (ret, cont, map (\(p_pc, err_pos, msg, r, m) -> 
                    let (_, newMsg, _, _) = mapBoundError (err_pos, msg, r, m)
                    in (p_pc, err_pos, newMsg, r, m)
               ) checks)

        While cond (Just invars) body ->
            let condVal = symEval l heap store cond
                checksC = map (\(p, msg, c) -> (pc, p, msg, c, symEval l heap store c)) (extractSafety l funcs cond)
                (_, dummyConts, _) = symExec 100 funcs l nextA heap M.empty (genExpr (BoolLit True)) body
                mutatedAddrs = nub $ concatMap (\(_, _, st, _) -> M.keys st) dummyConts
                havocStore = foldl (\s a -> M.insert a (genExpr (Var ("_havoc_" ++ show a ++ "_" ++ show nextA))) s) store mutatedAddrs
                invAssumptions = foldl (\acc inv -> genExpr (BinOp "&&" acc (symEval l heap havocStore inv))) (genExpr (BoolLit True)) invars
                exitPc = genExpr (BinOp "&&" invAssumptions (genExpr (UnOp "!" (symEval l heap havocStore condVal))))
                finalPc = genExpr (BinOp "&&" pc exitPc)
                (retS, contS, checksS) = symExec f funcs l nextA heap havocStore finalPc stmts
            in (retS, contS, checksC ++ checksS)
            
        _ -> 
            let (r, c, checks) = symExec f funcs l nextA heap store pc stmts
            in (r, c, checks)


-- ============================================================================
-- ANALYSIS HELPERS
-- ============================================================================

alloc :: String -> Type -> Value -> Analyzer Addr
alloc name ty val = do
    l <- getLayout
    addr <- gets nextAddr
    let sz = sizeOf l ty
    modify (\s -> s { nextAddr = addr + sz
                    , env = M.insert name addr (env s)
                    , heap = M.insert addr val (heap s)
                    , heapTypes = M.insert addr ty (heapTypes s) })
    return addr

getFootprint :: Layout -> Heap -> [Value] -> [Addr]
getFootprint l heap initialVals = 
    let startAddrs = [ a | VAddr a <- initialVals ]
        expandSize addr = case M.lookup addr (lTypes l) of Just ty -> [addr .. addr + sizeOf l ty - 1]; Nothing -> [addr]
        findReachable [] visited = visited
        findReachable (a:worklist) visited 
            | a `elem` visited = findReachable worklist visited
            | otherwise = 
                let block = expandSize a
                    vals = map (\addr -> M.findWithDefault VUnknown addr heap) block
                    newAddrs = [ ptr | VAddr ptr <- vals, ptr `notElem` visited ]
                in findReachable (newAddrs ++ worklist) (block ++ visited)
    in nub $ findReachable startAddrs []

buildSummaries :: Analyzer ()
buildSummaries = do
    funcMap <- gets funcs
    forM_ (M.toList funcMap) $ \(fname, funcDef) -> do
        let isAxiom = isJust (funcPostconds funcDef) && isJust (funcInvars funcDef)
        
        if isAxiom then
            modify (\s -> s { summaries = M.insert fname (FuncSummary [] []) (summaries s) })
        else do
            l <- getLayout
            let paramNames = map (\(Arg _ n) -> n) (funcArgs funcDef)
            let paramTypes = map (\(Arg t _) -> t) (funcArgs funcDef)
            
            let startAddr = 1000 
            let localEnv = M.fromList (zip paramNames [startAddr..])
            let localTypes = M.fromList (zip [startAddr..] paramTypes)
            
            let targetStartAddr = startAddr + length paramNames
            let (dummyHeap, dummyTypes, ptrMap) = foldl (\(h, ts, m) (name, ty, addr) -> 
                    case ty of
                        Ptr innerTy -> 
                            let tAddr = targetStartAddr + addr
                            in (M.insert addr (VAddr tAddr) h, M.insert tAddr innerTy ts, M.insert tAddr (name, innerTy) m)
                        _ -> (h, ts, m)
                  ) (M.empty, localTypes, M.empty) (zip3 paramNames paramTypes [startAddr..])

            let sandboxLayout = l { lEnv = localEnv, lTypes = dummyTypes }
            
            let maxAddr = targetStartAddr + length paramNames + 1000
            let (returns, continues, _) = symExec 1000 funcMap sandboxLayout maxAddr dummyHeap M.empty (genExpr (BoolLit True)) (funcBody funcDef)
            
            let allPaths = returns ++ map (\(_, _, st, pc) -> (pc, Nothing, st)) continues
            
            let pathExprs = mapMaybe (\(pc, mRet, store) ->
                    let retFact = case mRet of
                            Just retExpr -> [genExpr (BinOp "==" (genExpr (Var "res")) retExpr)]
                            Nothing -> []
                        ptrFacts = mapMaybe (\(targetAddr, (pName, _)) -> 
                                case M.lookup targetAddr store of
                                    Just newVal -> Just (genExpr (BinOp "==" (genExpr (Deref (genExpr (Var pName)))) newVal))
                                    Nothing -> Nothing
                            ) (M.toList ptrMap)
                        allFacts = retFact ++ ptrFacts
                    in if null allFacts then Nothing 
                       else Just (if pc == genExpr (BoolLit True) 
                                  then foldl1 (\acc f -> genExpr (BinOp "&&" acc f)) allFacts 
                                  else genExpr (BinOp "&&" pc (foldl1 (\acc f -> genExpr (BinOp "&&" acc f)) allFacts)))
                  ) allPaths
                  
            let computedPosts = if null pathExprs then [] else [foldl1 (\acc e -> genExpr (BinOp "||" acc e)) pathExprs]
            
            let mutatedAddrs = nub (concatMap (\(_, _, st) -> M.keys st) allPaths)
            let mutatedVars = [ pName | targetAddr <- mutatedAddrs, Just (pName, _) <- [M.lookup targetAddr ptrMap] ]
            
            modify (\s -> s { summaries = M.insert fname (FuncSummary mutatedVars computedPosts) (summaries s) })

registerCallFacts :: Maybe Expr -> String -> [Expr] -> Analyzer ()
registerCallFacts mAssignedVar fname argExprs = do
    callerLayout <- getLayout
    callerHeap <- gets heap
    funcMap <- gets funcs
    sumMap <- gets summaries
    
    case M.lookup fname funcMap of
        Just funcDef -> do
            let paramNames = map (\(Arg _ n) -> n) (funcArgs funcDef)
            let subs = zip (map (genExpr . Var) paramNames) argExprs
            
            let summary = M.findWithDefault (FuncSummary [] []) fname sumMap
            let explicitPost = fromMaybe [] (funcPostconds funcDef)

            let mutatedArgs = [ argExprs !! i | (i, name) <- zip [0..] paramNames, name `elem` modifiedParams summary ]
            argVals <- mapM evalExpr mutatedArgs
            let footprint = getFootprint callerLayout callerHeap argVals
            
            let mutatedCallerVars = [ name | (name, baseAddr) <- M.toList (lEnv callerLayout), Just ty <- [M.lookup baseAddr (lTypes callerLayout)], let sz = sizeOf callerLayout ty, any (\addr -> addr >= baseAddr && addr < baseAddr + sz) footprint ]
            
            modify (\s -> s { heap = foldr M.delete (heap s) footprint })
            modify (\s -> s { facts = filter (\f -> not (any (`elem` mutatedCallerVars) (extractVars f))) (facts s) })

            updatedHeap <- gets heap 

            let allPosts = explicitPost ++ implicitPosts summary
            let callerStandard = map (substituteMany subs) (concatMap splitAnds allPosts)
            
            let finalFacts = case mAssignedVar of 
                    Just varExpr -> map (substituteExpr (genExpr (Var "res")) varExpr) callerStandard
                    Nothing -> callerStandard

            let evaluatedFinalFacts = map (partialEval callerLayout updatedHeap) finalFacts

            modify (\s -> s { facts = facts s ++ evaluatedFinalFacts })
            
        Nothing -> do
            argVals <- mapM evalExpr argExprs
            let footprint = getFootprint callerLayout callerHeap argVals
            let mutatedCallerVars = [ name | (name, baseAddr) <- M.toList (lEnv callerLayout), Just ty <- [M.lookup baseAddr (lTypes callerLayout)], let sz = sizeOf callerLayout ty, any (\addr -> addr >= baseAddr && addr < baseAddr + sz) footprint ]
            
            modify (\s -> s { facts = filter (\f -> not (any (`elem` mutatedCallerVars) (extractVars f))) (facts s) })
            modify (\s -> s { heap = foldr M.delete (heap s) footprint })
            return ()

-- ============================================================================
-- CONCRETE EXECUTION ENGINE
-- ============================================================================

analyzeStmt :: Stmt -> Analyzer ()
analyzeStmt stmt@(Stmt pos stmtNode) = do
    ret <- gets returnVal
    case ret of
        Just _ -> return () 
        Nothing -> case stmtNode of
            Decl _ ty name mExpr -> do
                val <- case mExpr of Just expr -> evalExpr expr; Nothing -> return VUnknown
                _ <- alloc name ty val 
                case mExpr of Just (Expr _ (Call fname args)) -> registerCallFacts (Just (genExpr (Var name))) fname args; _ -> return ()
            
            Assign lhs expr -> do
                val <- evalExpr expr
                l <- getLayout
                h <- gets heap
                case lvalue l h lhs of
                    Just addr -> modify (\s -> s { heap = M.insert addr val (heap s) })
                    Nothing   -> return ()
                case expr of Expr _ (Call fname args) -> registerCallFacts (Just lhs) fname args; _ -> return ()
            
            ExprStmt callExpr@(Expr _ (Call fname args)) -> do
                _ <- evalExpr callExpr
                registerCallFacts Nothing fname args
                
            ExprStmt (Expr _ (PreInc lhs))  -> mutateHeap lhs (+ 1)
            ExprStmt (Expr _ (PostInc lhs)) -> mutateHeap lhs (+ 1)
            ExprStmt (Expr _ (PreDec lhs))  -> mutateHeap lhs (\x -> x - 1)
            ExprStmt (Expr _ (PostDec lhs)) -> mutateHeap lhs (\x -> x - 1)
            
            Block stmts -> mapM_ analyzeStmt stmts
            If cond thn els -> do
                condVal <- evalExpr cond
                case condVal of 
                    VBool True  -> mapM_ analyzeStmt thn
                    VBool False -> maybe (return ()) (mapM_ analyzeStmt) els
                    _           -> mapM_ analyzeStmt thn 
                
            While cond (Just invars) body -> do
                currHeap  <- gets heap
                currFacts <- gets facts
                currFuncs <- gets funcs
                l <- getLayout
                
                forM_ invars $ \inv -> do
                    let evalInv = partialEval l currHeap (symEval l currHeap M.empty inv)
                    let evalFacts = map (partialEval l currHeap) currFacts
                    isProven <- liftIO $ proveZ3 l currFuncs evalFacts evalInv
                    when (isProven == VBool False || isProven == VUnknown) $
                        modify (\s -> s { violations = ((pos, "Loop Base Case Failed", inv) : violations s) })
                        
                nxtA <- gets nextAddr
                let (_, dummyConts, _) = symExec 100 currFuncs l nxtA currHeap M.empty (genExpr (BoolLit True)) body
                let mutatedAddrs = nub $ concatMap (\(_, _, st, _) -> M.keys st) dummyConts
                let havocStore = foldl (\s a -> M.insert a (genExpr (Var ("_havoc_" ++ show a))) s) M.empty mutatedAddrs
                
                let symCond = symEval l currHeap havocStore cond
                let invAssumptions = map (symEval l currHeap havocStore) invars
                let startPc = if null invAssumptions then symCond else genExpr (BinOp "&&" (foldl1 (\acc i -> genExpr (BinOp "&&" acc i)) invAssumptions) symCond)
                
                let (_, symConts, _) = symExec 1000 currFuncs l nxtA currHeap havocStore startPc body
                
                forM_ symConts $ \(_, _, endStore, pathPc) -> do
                    forM_ invars $ \inv -> do
                        let endInv = symEval l currHeap endStore inv
                        let evalInv = partialEval l currHeap endInv
                        let evalFacts = map (partialEval l currHeap) (currFacts ++ invars ++ splitAnds pathPc)
                        isProven <- liftIO $ proveZ3 l currFuncs evalFacts evalInv
                        when (isProven == VBool False || isProven == VUnknown) $
                            modify (\s -> s { violations = ((pos, "Loop Inductive Step Failed", inv) : violations s) })
                            
                modify (\s -> s { facts = facts s ++ invars ++ [genExpr (UnOp "!" cond)] })
                forM_ mutatedAddrs $ \addr -> do
                    modify (\s -> s { heap = M.delete addr (heap s) })
                    
            While cond Nothing body -> do
                let unrollLimit = 5
                    unrolledStmts = foldr (\_ acc -> [Stmt pos (If cond (body ++ acc) Nothing)]) [] [1..unrollLimit]
                mapM_ analyzeStmt unrolledStmts

            Return mExpr -> do 
                case mExpr of 
                    Just expr -> do val <- evalExpr expr; modify (\s -> s { returnVal = Just val })
                    Nothing   -> modify (\s -> s { returnVal = Just VUnknown })
            _ -> return ()

mutateHeap :: Expr -> (Integer -> Integer) -> Analyzer ()
mutateHeap lhs op = do
    l <- getLayout
    h <- gets heap
    case lvalue l h lhs of
        Just addr -> do
            let newVal = case M.findWithDefault VUnknown addr h of VInt n -> VInt (op n); _ -> VUnknown
            modify (\s -> s { heap = M.insert addr newVal (heap s) })
        Nothing -> return ()


-- ============================================================================
-- PRETTY PRINTING
-- ============================================================================

prettyTop :: Expr -> String
prettyTop expr@(Expr _ node) = case node of
    BinOp op e1 e2 -> prettyExpr e1 ++ " " ++ op ++ " " ++ prettyExpr e2
    Ternary c t e  -> prettyTop c ++ " ? " ++ prettyTop t ++ " : " ++ prettyTop e
    _              -> prettyExpr expr

prettyExpr :: Expr -> String
prettyExpr (Expr _ node) = case node of
    Var x         -> x
    IntLit n      -> show n
    DoubleLit d   -> show d
    BoolLit True  -> "true"
    BoolLit False -> "false"
    CharLit c     -> show c
    StringLit s   -> show s
    Index e1 e2   -> prettyExpr e1 ++ "[" ++ prettyTop e2 ++ "]"
    Call f args   -> f ++ "(" ++ intercalate ", " (map prettyTop args) ++ ")"
    Field e p     -> prettyExpr e ++ "." ++ p
    Deref e       -> "*" ++ prettyExpr e
    AddrOf e      -> "&" ++ prettyExpr e
    UnOp op e     -> op ++ prettyExpr e
    PreInc e      -> "++" ++ prettyExpr e
    PreDec e      -> "--" ++ prettyExpr e
    PostInc e     -> prettyExpr e ++ "++"
    PostDec e     -> prettyExpr e ++ "--"
    Ternary c t e -> "(" ++ prettyTop c ++ " ? " ++ prettyTop t ++ " : " ++ prettyTop e ++ ")"
    BinOp op e1 e2-> "(" ++ prettyExpr e1 ++ " " ++ op ++ " " ++ prettyExpr e2 ++ ")"


-- ============================================================================
-- MAIN ENTRY POINT
-- ============================================================================

-- | Main execution function for the analyzer. Takes the AST, registers global definitions,
-- and iterates through each function to verify its body against its contracts.
runAnalyzer :: [TopLevel] -> IO [String]
runAnalyzer ast = 
    let 
        funcDefs   = M.fromList [ (funcName f, f) | DefFunc f <- ast ]
        globalDefs = [ g | g@(DefGlobal _ _ _ _) <- ast ]
        structDefs = M.fromList [ (name, fields) | DefStruct name fields <- ast ]
        unionDefs  = M.fromList [ (name, fields) | DefUnion name fields <- ast ]
        
        initialState = AnalyzerState M.empty M.empty M.empty structDefs unionDefs 1 [] funcDefs [] Nothing (M.fromList [])
        
        formatViolation :: (SourcePos, String, Expr) -> String
        formatViolation (pos, msg, expr) = 
            sourceName pos ++ ":" ++ 
            show (unPos (sourceLine pos)) ++ ":" ++ 
            show (unPos (sourceColumn pos)) ++ 
            " - " ++ msg ++ ": " ++ prettyTop expr

        setupGlobals = forM_ globalDefs $ \g -> case g of
            DefGlobal _ ty name mExpr -> do
                val <- case mExpr of Just expr -> evalExpr expr; Nothing -> return VUnknown
                _ <- alloc name ty val
                return ()
            _ -> return ()
            
        verifyFunc funcDef = do
            -- Optimization: Skip verifying functions that don't compute/mutate anything (axioms)
            let isAxiom = not (any hasComputation (funcBody funcDef))
                  where
                    hasComputation (Stmt _ (Assign _ _))         = True
                    hasComputation (Stmt _ (ExprStmt _))         = True
                    hasComputation (Stmt _ (If _ _ _))           = True
                    hasComputation (Stmt _ (While _ _ _))        = True
                    hasComputation (Stmt _ (For _ _ _ _))        = True
                    hasComputation (Stmt _ (Block stmts))        = any hasComputation stmts
                    hasComputation (Stmt _ (Decl _ _ _ (Just _)))= True 
                    hasComputation (Stmt _ (Return (Just _)))    = True
                    hasComputation _                             = False
                    
            unless isAxiom $ do
                globalEnv   <- gets env
                globalHeap  <- gets heap
                globalTypes <- gets heapTypes
                globalFacts <- gets facts
                globalNextA <- gets nextAddr
                currFuncs   <- gets funcs
                
                let paramNames    = map (\(Arg _ n) -> n) (funcArgs funcDef)
                let paramTypes    = map (\(Arg t _) -> t) (funcArgs funcDef)
                let startAddr     = globalNextA + 1000
                let localEnv      = M.fromList (zip paramNames [startAddr..]) `M.union` globalEnv
                let localTypesMap = M.fromList (zip [startAddr..] paramTypes) `M.union` globalTypes
                let startFacts    = concatMap splitAnds (fromMaybe [] (funcInvars funcDef))
                
                -- Initialize isolated function scope
                modify (\s -> s { env = localEnv, heapTypes = localTypesMap, facts = globalFacts ++ startFacts, nextAddr = startAddr + length paramNames, returnVal = Nothing })
                
                -- Fast concrete evaluation pass
                mapM_ analyzeStmt (funcBody funcDef)
                
                l <- getLayout
                
                -- Deep symbolic execution pass
                let (returns, continues, safetyObligations) = symExec 10000 currFuncs l (startAddr + length paramNames) globalHeap M.empty (genExpr (BoolLit True)) (funcBody funcDef)
                
                -- Prove all extracted safety obligations (like division by zero prevention)
                forM_ safetyObligations $ \(pathPc, errorPos, errMsg, readableCheck, mathCheck) -> do
                    let evalCheck = partialEval l globalHeap mathCheck
                    let pcSimplified = simplifyBool (partialEval l globalHeap pathPc)
                    if pcSimplified == genExpr (BoolLit False) then return () else do
                        let evalFacts = map (partialEval l globalHeap) (globalFacts ++ startFacts ++ splitAnds pcSimplified)
                        isProven <- liftIO $ proveZ3 l currFuncs evalFacts evalCheck
                        when (isProven == VBool False || isProven == VUnknown) $
                            modify (\s -> s { violations = ((errorPos, errMsg, readableCheck) : violations s) })

                -- Prove user-defined postconditions
                let allPaths = returns ++ map (\(_, _, st, p) -> (p, Nothing, st)) continues
                let posts = fromMaybe [] (funcPostconds funcDef)
                
                forM_ allPaths $ \(pathPc, mRet, store) -> do
                    let returnSub = case mRet of Just r -> substituteExpr (genExpr (Var "res")) r; Nothing -> id
                    forM_ posts $ \post@(Expr postPos _) -> do
                        let finalPost = returnSub post
                        let evalPost = symEval l globalHeap store finalPost
                        let evalPostConcrete = partialEval l globalHeap evalPost
                        let evalFacts = map (partialEval l globalHeap) (globalFacts ++ startFacts ++ splitAnds pathPc)
                        
                        isProven <- liftIO $ proveZ3 l currFuncs evalFacts evalPostConcrete
                        when (isProven == VBool False || isProven == VUnknown) $
                            modify (\s -> s { violations = ((postPos, "Postcondition Failed in: " ++ funcName funcDef, post) : violations s) })
                            
                -- Restore global state before verifying the next function
                modify (\s -> s { env = globalEnv, heap = globalHeap, heapTypes = globalTypes, facts = globalFacts, nextAddr = globalNextA, returnVal = Nothing })

    in do
        finalState <- execStateT (setupGlobals >> buildSummaries >> mapM_ verifyFunc (M.elems funcDefs)) initialState
        return $ map formatViolation (reverse $ violations finalState)